### ISSUE TITLE
ENode是否可以配置EventSouring开关？

### ISSUE THREAD

**Issue by menethil** [tangxuehua/enode#74]
目前 ENode 框架依赖数据库加入

                    Id = even.AggregateRootId,
                    CreatedOn = even.Timestamp,
                    UpdatedOn = even.Timestamp,
                    Version = even.Version

这几个字段，而有些项目旧数据库是不允许新增字段的，这种情况下是否ENode就无法使用？

**Comment by tangxuehua** [comment]
是的
在2018年07月01日 08:04，Menethil 写道：

目前 ENode 框架依赖数据库加入

                Id = even.AggregateRootId,
                CreatedOn = even.Timestamp,
                UpdatedOn = even.Timestamp,
                Version = even.Version


这几个字段，而有些项目旧数据库是不允许新增字段的，这种情况下是否ENode就无法使用？
