### ISSUE TITLE
获取聚合根Handle时如果是级联继承，是否应该将子类以及父类的Handle一起加载

### ISSUE THREAD

**Issue by xbOnline** [tangxuehua/enode#77]
public Action<IAggregateRoot, IDomainEvent> GetInternalEventHandler(Type aggregateRootType, Type eventType)
        {
            IDictionary<Type, Action<IAggregateRoot, IDomainEvent>> eventHandlerDic;
            if (!_mappings.TryGetValue(aggregateRootType, out eventHandlerDic)) return null;
            Action<IAggregateRoot, IDomainEvent> eventHandler;
            return eventHandlerDic.TryGetValue(eventType, out eventHandler) ? eventHandler : null;
        }
以上是否应该将父类的handle一起加载？

**Comment by tangxuehua** [comment]
fixed.
