### ISSUE TITLE
CommandResultProcessor挂起时，SendReplyService里的SocketRemotingClient遗漏了，没有停止ReconnectServer()

### ISSUE THREAD

**Issue by rocleegithub** [tangxuehua/enode#78]
private void ScanInactiveRemotingClients()
        {
            var inactiveList = new List<KeyValuePair<string, SocketRemotingClient>>();
            foreach (var pair in _remotingClientDict)
            {
                if (!pair.Value.IsConnected)
                {
                    inactiveList.Add(pair);
                }
            }
            foreach (var pair in inactiveList)
            {
                if (_remotingClientDict.TryRemove(pair.Key, out SocketRemotingClient removed))
                {
                    removed.Shutdown();//缺少了这个操作
                    _logger.InfoFormat("Removed disconnected command remoting client, remotingAddress: {0}", pair.Key);
                }
            }
        }

**Comment by tangxuehua** [comment]
merged your pull request.
