### ISSUE TITLE
希望能用微软的依赖注入框架

### ISSUE THREAD

**Issue by cocosip** [tangxuehua/enode#89]
希望能用微软的依赖注入框架。目前我们的项目由于有用到SkyAPM,里面所用的依赖注入框架为AspectCore-Framework，并且用到了里面AOP的一些特性。 因此如果使用ENode项目中就会存在3套不同的框架，适配起来十分的麻烦。并且可能会产生一些未知的bug。ECommon,ENode中的依赖注入的需求都不复杂,微软的依赖注入框架完全能够满足。希望汤总能考虑一下。

_Originally posted by @cocosip in https://github.com/tangxuehua/enode/issues/76#issuecomment-618482861_

**Comment by berkaroad** [comment]
如果以 AspectCore-Framework 为主，你可以基于此做一个适配，接收参数为 Autofac.IContainer，目前ENode的Ioc默认是Autofac，你只要在enode初始化ioc完成后，将Autofac.IContainer 传入你写的适配中，将autofac中注册的，也注册到 AspectCore-Framework 即可

**Comment by berkaroad** [comment]
或者自己实现用于Enode（应该是ECommon）的适配，来实现基于AspectCore-Framework的IoC

**Comment by tangxuehua** [comment]
微软的DI不考虑支持了，如楼上所述，你可以自己实现适配，很简单的。
